tap "phrase/brewed"
tap "thoughtbot/formulae"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/versions"
tap "caskroom/cask"
brew "autoconf"
brew "awscli"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "libusb"
brew "pinentry"
brew "gnupg"
brew "blackbox"
brew "boost"
brew "emacs"
brew "cask"
brew "openssl"
brew "python"
brew "certbot"
brew "direnv"
brew "pth"
brew "dirmngr"
brew "fasd"
brew "pcre2"
brew "fish"
brew "git"
brew "git-secrets"
brew "go"
brew "gpg-agent"
brew "lua"
brew "highlight"
brew "hub"
brew "jq"
brew "libevent"
brew "libusb-compat"
brew "makedepend"
brew "mas"
brew "micro"
brew "node"
brew "pinentry-mac"
brew "python3"
brew "postgresql", restart_service: true
brew "ruby-build"
brew "rbenv", args: ["HEAD"]
brew "rbenv-bundler"
brew "rbenv-gemset"
brew "reattach-to-user-namespace"
brew "screenfetch"
brew "tmux"
brew "v8"
brew "phrase/brewed/phraseapp"
brew "thoughtbot/formulae/rcm"
cask "a-better-finder-rename"
cask "alfred"
cask "backblaze"
cask "bartender"
cask "betterzipql"
cask "caffeine"
cask "choosy"
cask "daisydisk"
cask "firefox"
cask "gas-mask"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-drive"
cask "hazel"
cask "hipchat"
cask "hocus-focus"
cask "imagealpha"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "joinme"
cask "kaleidoscope"
cask "keka"
cask "keybase"
cask "licecap"
cask "multifirefox"
cask "onyx"
cask "paw"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "rowanj-gitx"
cask "scrutiny"
cask "sequel-pro"
cask "sketch"
cask "sketch-beta"
cask "sublime-text"
cask "superduper"
cask "suspicious-package"
cask "taskpaper"
cask "transmit"
cask "typora"
cask "viscosity"
cask "vmware-fusion"
cask "webpquicklook"
mas "1Password", id: 443987910
mas "BreakTime", id: 427475982
mas "Fantastical 2", id: 975937182
mas "JPEGmini", id: 498944723
mas "Keynote", id: 409183694
mas "Moom", id: 419330170
mas "Numbers", id: 409203825
mas "OmniFocus", id: 867299399
mas "Pages", id: 409201541
mas "Patterns", id: 429449079
mas "PDF Expert", id: 1055273043
mas "Pixelmator", id: 407963104
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "Soulver", id: 413965349
mas "Tweetbot", id: 557168941
mas "UlyssesMac", id: 1225570693
mas "xScope", id: 889428659
